### ISSUE TITLE
Addon Cut Scene Activation

### ISSUE THREAD

**Issue by RyGuyRed1** [hascat/Hydrate#1]
The addon can activate during cut scenes and can't be closed/minimized during the cut scene. Any way to fix this?

**Comment by RyGuyRed1** [comment]
Um... I have absolutely no experience coding, but I came across these pages and thought they might be useful somehow. I'll wait a few days before trying to change the code myself.
https://wow.gamepedia.com/API_IsInCinematicScene
https://wow.gamepedia.com/API_InCinematic

**Comment by hascat** [comment]
Thanks for the bug report! This should be fixed in the latest version.
